// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastream.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_datastream_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_datastream_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_datastream_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_datastream_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_datastream_2eproto;
class AttitudePayload;
struct AttitudePayloadDefaultTypeInternal;
extern AttitudePayloadDefaultTypeInternal _AttitudePayload_default_instance_;
class BatteryStatusPayload;
struct BatteryStatusPayloadDefaultTypeInternal;
extern BatteryStatusPayloadDefaultTypeInternal _BatteryStatusPayload_default_instance_;
class DataStreamRequest;
struct DataStreamRequestDefaultTypeInternal;
extern DataStreamRequestDefaultTypeInternal _DataStreamRequest_default_instance_;
class DataStreamResponse;
struct DataStreamResponseDefaultTypeInternal;
extern DataStreamResponseDefaultTypeInternal _DataStreamResponse_default_instance_;
class GlobalPositionIntPayload;
struct GlobalPositionIntPayloadDefaultTypeInternal;
extern GlobalPositionIntPayloadDefaultTypeInternal _GlobalPositionIntPayload_default_instance_;
class HeartbeatPayload;
struct HeartbeatPayloadDefaultTypeInternal;
extern HeartbeatPayloadDefaultTypeInternal _HeartbeatPayload_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::AttitudePayload* Arena::CreateMaybeMessage<::AttitudePayload>(Arena*);
template<> ::BatteryStatusPayload* Arena::CreateMaybeMessage<::BatteryStatusPayload>(Arena*);
template<> ::DataStreamRequest* Arena::CreateMaybeMessage<::DataStreamRequest>(Arena*);
template<> ::DataStreamResponse* Arena::CreateMaybeMessage<::DataStreamResponse>(Arena*);
template<> ::GlobalPositionIntPayload* Arena::CreateMaybeMessage<::GlobalPositionIntPayload>(Arena*);
template<> ::HeartbeatPayload* Arena::CreateMaybeMessage<::HeartbeatPayload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class DataStreamRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DataStreamRequest) */ {
 public:
  inline DataStreamRequest() : DataStreamRequest(nullptr) {}
  ~DataStreamRequest() override;
  explicit PROTOBUF_CONSTEXPR DataStreamRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DataStreamRequest(const DataStreamRequest& from);
  DataStreamRequest(DataStreamRequest&& from) noexcept
    : DataStreamRequest() {
    *this = ::std::move(from);
  }

  inline DataStreamRequest& operator=(const DataStreamRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataStreamRequest& operator=(DataStreamRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DataStreamRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DataStreamRequest* internal_default_instance() {
    return reinterpret_cast<const DataStreamRequest*>(
               &_DataStreamRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DataStreamRequest& a, DataStreamRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DataStreamRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataStreamRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DataStreamRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DataStreamRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DataStreamRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DataStreamRequest& from) {
    DataStreamRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataStreamRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DataStreamRequest";
  }
  protected:
  explicit DataStreamRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kConnIdFieldNumber = 2,
  };
  // string type = 1;
  void clear_type();
  const std::string& type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // string conn_id = 2;
  void clear_conn_id();
  const std::string& conn_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_conn_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_conn_id();
  PROTOBUF_NODISCARD std::string* release_conn_id();
  void set_allocated_conn_id(std::string* conn_id);
  private:
  const std::string& _internal_conn_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_conn_id(const std::string& value);
  std::string* _internal_mutable_conn_id();
  public:

  // @@protoc_insertion_point(class_scope:DataStreamRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr conn_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_datastream_2eproto;
};
// -------------------------------------------------------------------

class DataStreamResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DataStreamResponse) */ {
 public:
  inline DataStreamResponse() : DataStreamResponse(nullptr) {}
  ~DataStreamResponse() override;
  explicit PROTOBUF_CONSTEXPR DataStreamResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DataStreamResponse(const DataStreamResponse& from);
  DataStreamResponse(DataStreamResponse&& from) noexcept
    : DataStreamResponse() {
    *this = ::std::move(from);
  }

  inline DataStreamResponse& operator=(const DataStreamResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataStreamResponse& operator=(DataStreamResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DataStreamResponse& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kHeartbeat = 10,
    kGlobalPositionInt = 11,
    kAttitude = 12,
    kBatteryStatus = 13,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const DataStreamResponse* internal_default_instance() {
    return reinterpret_cast<const DataStreamResponse*>(
               &_DataStreamResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DataStreamResponse& a, DataStreamResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DataStreamResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataStreamResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DataStreamResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DataStreamResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DataStreamResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DataStreamResponse& from) {
    DataStreamResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataStreamResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DataStreamResponse";
  }
  protected:
  explicit DataStreamResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 1,
    kSrcSystemFieldNumber = 2,
    kSrcComponentFieldNumber = 3,
    kHeartbeatFieldNumber = 10,
    kGlobalPositionIntFieldNumber = 11,
    kAttitudeFieldNumber = 12,
    kBatteryStatusFieldNumber = 13,
  };
  // string content = 1;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // string src_system = 2;
  void clear_src_system();
  const std::string& src_system() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_src_system(ArgT0&& arg0, ArgT... args);
  std::string* mutable_src_system();
  PROTOBUF_NODISCARD std::string* release_src_system();
  void set_allocated_src_system(std::string* src_system);
  private:
  const std::string& _internal_src_system() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_src_system(const std::string& value);
  std::string* _internal_mutable_src_system();
  public:

  // string src_component = 3;
  void clear_src_component();
  const std::string& src_component() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_src_component(ArgT0&& arg0, ArgT... args);
  std::string* mutable_src_component();
  PROTOBUF_NODISCARD std::string* release_src_component();
  void set_allocated_src_component(std::string* src_component);
  private:
  const std::string& _internal_src_component() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_src_component(const std::string& value);
  std::string* _internal_mutable_src_component();
  public:

  // .HeartbeatPayload heartbeat = 10;
  bool has_heartbeat() const;
  private:
  bool _internal_has_heartbeat() const;
  public:
  void clear_heartbeat();
  const ::HeartbeatPayload& heartbeat() const;
  PROTOBUF_NODISCARD ::HeartbeatPayload* release_heartbeat();
  ::HeartbeatPayload* mutable_heartbeat();
  void set_allocated_heartbeat(::HeartbeatPayload* heartbeat);
  private:
  const ::HeartbeatPayload& _internal_heartbeat() const;
  ::HeartbeatPayload* _internal_mutable_heartbeat();
  public:
  void unsafe_arena_set_allocated_heartbeat(
      ::HeartbeatPayload* heartbeat);
  ::HeartbeatPayload* unsafe_arena_release_heartbeat();

  // .GlobalPositionIntPayload global_position_int = 11;
  bool has_global_position_int() const;
  private:
  bool _internal_has_global_position_int() const;
  public:
  void clear_global_position_int();
  const ::GlobalPositionIntPayload& global_position_int() const;
  PROTOBUF_NODISCARD ::GlobalPositionIntPayload* release_global_position_int();
  ::GlobalPositionIntPayload* mutable_global_position_int();
  void set_allocated_global_position_int(::GlobalPositionIntPayload* global_position_int);
  private:
  const ::GlobalPositionIntPayload& _internal_global_position_int() const;
  ::GlobalPositionIntPayload* _internal_mutable_global_position_int();
  public:
  void unsafe_arena_set_allocated_global_position_int(
      ::GlobalPositionIntPayload* global_position_int);
  ::GlobalPositionIntPayload* unsafe_arena_release_global_position_int();

  // .AttitudePayload attitude = 12;
  bool has_attitude() const;
  private:
  bool _internal_has_attitude() const;
  public:
  void clear_attitude();
  const ::AttitudePayload& attitude() const;
  PROTOBUF_NODISCARD ::AttitudePayload* release_attitude();
  ::AttitudePayload* mutable_attitude();
  void set_allocated_attitude(::AttitudePayload* attitude);
  private:
  const ::AttitudePayload& _internal_attitude() const;
  ::AttitudePayload* _internal_mutable_attitude();
  public:
  void unsafe_arena_set_allocated_attitude(
      ::AttitudePayload* attitude);
  ::AttitudePayload* unsafe_arena_release_attitude();

  // .BatteryStatusPayload battery_status = 13;
  bool has_battery_status() const;
  private:
  bool _internal_has_battery_status() const;
  public:
  void clear_battery_status();
  const ::BatteryStatusPayload& battery_status() const;
  PROTOBUF_NODISCARD ::BatteryStatusPayload* release_battery_status();
  ::BatteryStatusPayload* mutable_battery_status();
  void set_allocated_battery_status(::BatteryStatusPayload* battery_status);
  private:
  const ::BatteryStatusPayload& _internal_battery_status() const;
  ::BatteryStatusPayload* _internal_mutable_battery_status();
  public:
  void unsafe_arena_set_allocated_battery_status(
      ::BatteryStatusPayload* battery_status);
  ::BatteryStatusPayload* unsafe_arena_release_battery_status();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:DataStreamResponse)
 private:
  class _Internal;
  void set_has_heartbeat();
  void set_has_global_position_int();
  void set_has_attitude();
  void set_has_battery_status();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr src_system_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr src_component_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::HeartbeatPayload* heartbeat_;
      ::GlobalPositionIntPayload* global_position_int_;
      ::AttitudePayload* attitude_;
      ::BatteryStatusPayload* battery_status_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_datastream_2eproto;
};
// -------------------------------------------------------------------

class HeartbeatPayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HeartbeatPayload) */ {
 public:
  inline HeartbeatPayload() : HeartbeatPayload(nullptr) {}
  ~HeartbeatPayload() override;
  explicit PROTOBUF_CONSTEXPR HeartbeatPayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartbeatPayload(const HeartbeatPayload& from);
  HeartbeatPayload(HeartbeatPayload&& from) noexcept
    : HeartbeatPayload() {
    *this = ::std::move(from);
  }

  inline HeartbeatPayload& operator=(const HeartbeatPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartbeatPayload& operator=(HeartbeatPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartbeatPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartbeatPayload* internal_default_instance() {
    return reinterpret_cast<const HeartbeatPayload*>(
               &_HeartbeatPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HeartbeatPayload& a, HeartbeatPayload& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartbeatPayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartbeatPayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartbeatPayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartbeatPayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeartbeatPayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeartbeatPayload& from) {
    HeartbeatPayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartbeatPayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HeartbeatPayload";
  }
  protected:
  explicit HeartbeatPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kAutopilotFieldNumber = 2,
    kBaseModeFieldNumber = 3,
    kSystemStatusFieldNumber = 4,
    kCustomModeFieldNumber = 5,
    kMavlinkVersionFieldNumber = 6,
  };
  // uint32 type = 1;
  void clear_type();
  uint32_t type() const;
  void set_type(uint32_t value);
  private:
  uint32_t _internal_type() const;
  void _internal_set_type(uint32_t value);
  public:

  // uint32 autopilot = 2;
  void clear_autopilot();
  uint32_t autopilot() const;
  void set_autopilot(uint32_t value);
  private:
  uint32_t _internal_autopilot() const;
  void _internal_set_autopilot(uint32_t value);
  public:

  // uint32 base_mode = 3;
  void clear_base_mode();
  uint32_t base_mode() const;
  void set_base_mode(uint32_t value);
  private:
  uint32_t _internal_base_mode() const;
  void _internal_set_base_mode(uint32_t value);
  public:

  // uint32 system_status = 4;
  void clear_system_status();
  uint32_t system_status() const;
  void set_system_status(uint32_t value);
  private:
  uint32_t _internal_system_status() const;
  void _internal_set_system_status(uint32_t value);
  public:

  // uint32 custom_mode = 5;
  void clear_custom_mode();
  uint32_t custom_mode() const;
  void set_custom_mode(uint32_t value);
  private:
  uint32_t _internal_custom_mode() const;
  void _internal_set_custom_mode(uint32_t value);
  public:

  // uint32 mavlink_version = 6;
  void clear_mavlink_version();
  uint32_t mavlink_version() const;
  void set_mavlink_version(uint32_t value);
  private:
  uint32_t _internal_mavlink_version() const;
  void _internal_set_mavlink_version(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HeartbeatPayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t type_;
    uint32_t autopilot_;
    uint32_t base_mode_;
    uint32_t system_status_;
    uint32_t custom_mode_;
    uint32_t mavlink_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_datastream_2eproto;
};
// -------------------------------------------------------------------

class GlobalPositionIntPayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GlobalPositionIntPayload) */ {
 public:
  inline GlobalPositionIntPayload() : GlobalPositionIntPayload(nullptr) {}
  ~GlobalPositionIntPayload() override;
  explicit PROTOBUF_CONSTEXPR GlobalPositionIntPayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GlobalPositionIntPayload(const GlobalPositionIntPayload& from);
  GlobalPositionIntPayload(GlobalPositionIntPayload&& from) noexcept
    : GlobalPositionIntPayload() {
    *this = ::std::move(from);
  }

  inline GlobalPositionIntPayload& operator=(const GlobalPositionIntPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline GlobalPositionIntPayload& operator=(GlobalPositionIntPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GlobalPositionIntPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const GlobalPositionIntPayload* internal_default_instance() {
    return reinterpret_cast<const GlobalPositionIntPayload*>(
               &_GlobalPositionIntPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GlobalPositionIntPayload& a, GlobalPositionIntPayload& b) {
    a.Swap(&b);
  }
  inline void Swap(GlobalPositionIntPayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GlobalPositionIntPayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GlobalPositionIntPayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GlobalPositionIntPayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GlobalPositionIntPayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GlobalPositionIntPayload& from) {
    GlobalPositionIntPayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GlobalPositionIntPayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GlobalPositionIntPayload";
  }
  protected:
  explicit GlobalPositionIntPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
  };
  // uint32 type = 1;
  void clear_type();
  uint32_t type() const;
  void set_type(uint32_t value);
  private:
  uint32_t _internal_type() const;
  void _internal_set_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:GlobalPositionIntPayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_datastream_2eproto;
};
// -------------------------------------------------------------------

class AttitudePayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AttitudePayload) */ {
 public:
  inline AttitudePayload() : AttitudePayload(nullptr) {}
  ~AttitudePayload() override;
  explicit PROTOBUF_CONSTEXPR AttitudePayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AttitudePayload(const AttitudePayload& from);
  AttitudePayload(AttitudePayload&& from) noexcept
    : AttitudePayload() {
    *this = ::std::move(from);
  }

  inline AttitudePayload& operator=(const AttitudePayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline AttitudePayload& operator=(AttitudePayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AttitudePayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const AttitudePayload* internal_default_instance() {
    return reinterpret_cast<const AttitudePayload*>(
               &_AttitudePayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AttitudePayload& a, AttitudePayload& b) {
    a.Swap(&b);
  }
  inline void Swap(AttitudePayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AttitudePayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AttitudePayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AttitudePayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AttitudePayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AttitudePayload& from) {
    AttitudePayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AttitudePayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AttitudePayload";
  }
  protected:
  explicit AttitudePayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
  };
  // uint32 type = 1;
  void clear_type();
  uint32_t type() const;
  void set_type(uint32_t value);
  private:
  uint32_t _internal_type() const;
  void _internal_set_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:AttitudePayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_datastream_2eproto;
};
// -------------------------------------------------------------------

class BatteryStatusPayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:BatteryStatusPayload) */ {
 public:
  inline BatteryStatusPayload() : BatteryStatusPayload(nullptr) {}
  ~BatteryStatusPayload() override;
  explicit PROTOBUF_CONSTEXPR BatteryStatusPayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BatteryStatusPayload(const BatteryStatusPayload& from);
  BatteryStatusPayload(BatteryStatusPayload&& from) noexcept
    : BatteryStatusPayload() {
    *this = ::std::move(from);
  }

  inline BatteryStatusPayload& operator=(const BatteryStatusPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatteryStatusPayload& operator=(BatteryStatusPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatteryStatusPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const BatteryStatusPayload* internal_default_instance() {
    return reinterpret_cast<const BatteryStatusPayload*>(
               &_BatteryStatusPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(BatteryStatusPayload& a, BatteryStatusPayload& b) {
    a.Swap(&b);
  }
  inline void Swap(BatteryStatusPayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatteryStatusPayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatteryStatusPayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BatteryStatusPayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BatteryStatusPayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BatteryStatusPayload& from) {
    BatteryStatusPayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatteryStatusPayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "BatteryStatusPayload";
  }
  protected:
  explicit BatteryStatusPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
  };
  // uint32 type = 1;
  void clear_type();
  uint32_t type() const;
  void set_type(uint32_t value);
  private:
  uint32_t _internal_type() const;
  void _internal_set_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:BatteryStatusPayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_datastream_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DataStreamRequest

// string type = 1;
inline void DataStreamRequest::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& DataStreamRequest::type() const {
  // @@protoc_insertion_point(field_get:DataStreamRequest.type)
  return _internal_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DataStreamRequest::set_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DataStreamRequest.type)
}
inline std::string* DataStreamRequest::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:DataStreamRequest.type)
  return _s;
}
inline const std::string& DataStreamRequest::_internal_type() const {
  return _impl_.type_.Get();
}
inline void DataStreamRequest::_internal_set_type(const std::string& value) {
  
  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* DataStreamRequest::_internal_mutable_type() {
  
  return _impl_.type_.Mutable(GetArenaForAllocation());
}
inline std::string* DataStreamRequest::release_type() {
  // @@protoc_insertion_point(field_release:DataStreamRequest.type)
  return _impl_.type_.Release();
}
inline void DataStreamRequest::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  _impl_.type_.SetAllocated(type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.type_.IsDefault()) {
    _impl_.type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DataStreamRequest.type)
}

// string conn_id = 2;
inline void DataStreamRequest::clear_conn_id() {
  _impl_.conn_id_.ClearToEmpty();
}
inline const std::string& DataStreamRequest::conn_id() const {
  // @@protoc_insertion_point(field_get:DataStreamRequest.conn_id)
  return _internal_conn_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DataStreamRequest::set_conn_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.conn_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DataStreamRequest.conn_id)
}
inline std::string* DataStreamRequest::mutable_conn_id() {
  std::string* _s = _internal_mutable_conn_id();
  // @@protoc_insertion_point(field_mutable:DataStreamRequest.conn_id)
  return _s;
}
inline const std::string& DataStreamRequest::_internal_conn_id() const {
  return _impl_.conn_id_.Get();
}
inline void DataStreamRequest::_internal_set_conn_id(const std::string& value) {
  
  _impl_.conn_id_.Set(value, GetArenaForAllocation());
}
inline std::string* DataStreamRequest::_internal_mutable_conn_id() {
  
  return _impl_.conn_id_.Mutable(GetArenaForAllocation());
}
inline std::string* DataStreamRequest::release_conn_id() {
  // @@protoc_insertion_point(field_release:DataStreamRequest.conn_id)
  return _impl_.conn_id_.Release();
}
inline void DataStreamRequest::set_allocated_conn_id(std::string* conn_id) {
  if (conn_id != nullptr) {
    
  } else {
    
  }
  _impl_.conn_id_.SetAllocated(conn_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.conn_id_.IsDefault()) {
    _impl_.conn_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DataStreamRequest.conn_id)
}

// -------------------------------------------------------------------

// DataStreamResponse

// string content = 1;
inline void DataStreamResponse::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& DataStreamResponse::content() const {
  // @@protoc_insertion_point(field_get:DataStreamResponse.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DataStreamResponse::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DataStreamResponse.content)
}
inline std::string* DataStreamResponse::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:DataStreamResponse.content)
  return _s;
}
inline const std::string& DataStreamResponse::_internal_content() const {
  return _impl_.content_.Get();
}
inline void DataStreamResponse::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* DataStreamResponse::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* DataStreamResponse::release_content() {
  // @@protoc_insertion_point(field_release:DataStreamResponse.content)
  return _impl_.content_.Release();
}
inline void DataStreamResponse::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DataStreamResponse.content)
}

// string src_system = 2;
inline void DataStreamResponse::clear_src_system() {
  _impl_.src_system_.ClearToEmpty();
}
inline const std::string& DataStreamResponse::src_system() const {
  // @@protoc_insertion_point(field_get:DataStreamResponse.src_system)
  return _internal_src_system();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DataStreamResponse::set_src_system(ArgT0&& arg0, ArgT... args) {
 
 _impl_.src_system_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DataStreamResponse.src_system)
}
inline std::string* DataStreamResponse::mutable_src_system() {
  std::string* _s = _internal_mutable_src_system();
  // @@protoc_insertion_point(field_mutable:DataStreamResponse.src_system)
  return _s;
}
inline const std::string& DataStreamResponse::_internal_src_system() const {
  return _impl_.src_system_.Get();
}
inline void DataStreamResponse::_internal_set_src_system(const std::string& value) {
  
  _impl_.src_system_.Set(value, GetArenaForAllocation());
}
inline std::string* DataStreamResponse::_internal_mutable_src_system() {
  
  return _impl_.src_system_.Mutable(GetArenaForAllocation());
}
inline std::string* DataStreamResponse::release_src_system() {
  // @@protoc_insertion_point(field_release:DataStreamResponse.src_system)
  return _impl_.src_system_.Release();
}
inline void DataStreamResponse::set_allocated_src_system(std::string* src_system) {
  if (src_system != nullptr) {
    
  } else {
    
  }
  _impl_.src_system_.SetAllocated(src_system, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.src_system_.IsDefault()) {
    _impl_.src_system_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DataStreamResponse.src_system)
}

// string src_component = 3;
inline void DataStreamResponse::clear_src_component() {
  _impl_.src_component_.ClearToEmpty();
}
inline const std::string& DataStreamResponse::src_component() const {
  // @@protoc_insertion_point(field_get:DataStreamResponse.src_component)
  return _internal_src_component();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DataStreamResponse::set_src_component(ArgT0&& arg0, ArgT... args) {
 
 _impl_.src_component_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DataStreamResponse.src_component)
}
inline std::string* DataStreamResponse::mutable_src_component() {
  std::string* _s = _internal_mutable_src_component();
  // @@protoc_insertion_point(field_mutable:DataStreamResponse.src_component)
  return _s;
}
inline const std::string& DataStreamResponse::_internal_src_component() const {
  return _impl_.src_component_.Get();
}
inline void DataStreamResponse::_internal_set_src_component(const std::string& value) {
  
  _impl_.src_component_.Set(value, GetArenaForAllocation());
}
inline std::string* DataStreamResponse::_internal_mutable_src_component() {
  
  return _impl_.src_component_.Mutable(GetArenaForAllocation());
}
inline std::string* DataStreamResponse::release_src_component() {
  // @@protoc_insertion_point(field_release:DataStreamResponse.src_component)
  return _impl_.src_component_.Release();
}
inline void DataStreamResponse::set_allocated_src_component(std::string* src_component) {
  if (src_component != nullptr) {
    
  } else {
    
  }
  _impl_.src_component_.SetAllocated(src_component, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.src_component_.IsDefault()) {
    _impl_.src_component_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DataStreamResponse.src_component)
}

// .HeartbeatPayload heartbeat = 10;
inline bool DataStreamResponse::_internal_has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline bool DataStreamResponse::has_heartbeat() const {
  return _internal_has_heartbeat();
}
inline void DataStreamResponse::set_has_heartbeat() {
  _impl_._oneof_case_[0] = kHeartbeat;
}
inline void DataStreamResponse::clear_heartbeat() {
  if (_internal_has_heartbeat()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.heartbeat_;
    }
    clear_has_payload();
  }
}
inline ::HeartbeatPayload* DataStreamResponse::release_heartbeat() {
  // @@protoc_insertion_point(field_release:DataStreamResponse.heartbeat)
  if (_internal_has_heartbeat()) {
    clear_has_payload();
    ::HeartbeatPayload* temp = _impl_.payload_.heartbeat_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::HeartbeatPayload& DataStreamResponse::_internal_heartbeat() const {
  return _internal_has_heartbeat()
      ? *_impl_.payload_.heartbeat_
      : reinterpret_cast< ::HeartbeatPayload&>(::_HeartbeatPayload_default_instance_);
}
inline const ::HeartbeatPayload& DataStreamResponse::heartbeat() const {
  // @@protoc_insertion_point(field_get:DataStreamResponse.heartbeat)
  return _internal_heartbeat();
}
inline ::HeartbeatPayload* DataStreamResponse::unsafe_arena_release_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:DataStreamResponse.heartbeat)
  if (_internal_has_heartbeat()) {
    clear_has_payload();
    ::HeartbeatPayload* temp = _impl_.payload_.heartbeat_;
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void DataStreamResponse::unsafe_arena_set_allocated_heartbeat(::HeartbeatPayload* heartbeat) {
  clear_payload();
  if (heartbeat) {
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DataStreamResponse.heartbeat)
}
inline ::HeartbeatPayload* DataStreamResponse::_internal_mutable_heartbeat() {
  if (!_internal_has_heartbeat()) {
    clear_payload();
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = CreateMaybeMessage< ::HeartbeatPayload >(GetArenaForAllocation());
  }
  return _impl_.payload_.heartbeat_;
}
inline ::HeartbeatPayload* DataStreamResponse::mutable_heartbeat() {
  ::HeartbeatPayload* _msg = _internal_mutable_heartbeat();
  // @@protoc_insertion_point(field_mutable:DataStreamResponse.heartbeat)
  return _msg;
}

// .GlobalPositionIntPayload global_position_int = 11;
inline bool DataStreamResponse::_internal_has_global_position_int() const {
  return payload_case() == kGlobalPositionInt;
}
inline bool DataStreamResponse::has_global_position_int() const {
  return _internal_has_global_position_int();
}
inline void DataStreamResponse::set_has_global_position_int() {
  _impl_._oneof_case_[0] = kGlobalPositionInt;
}
inline void DataStreamResponse::clear_global_position_int() {
  if (_internal_has_global_position_int()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.global_position_int_;
    }
    clear_has_payload();
  }
}
inline ::GlobalPositionIntPayload* DataStreamResponse::release_global_position_int() {
  // @@protoc_insertion_point(field_release:DataStreamResponse.global_position_int)
  if (_internal_has_global_position_int()) {
    clear_has_payload();
    ::GlobalPositionIntPayload* temp = _impl_.payload_.global_position_int_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.global_position_int_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::GlobalPositionIntPayload& DataStreamResponse::_internal_global_position_int() const {
  return _internal_has_global_position_int()
      ? *_impl_.payload_.global_position_int_
      : reinterpret_cast< ::GlobalPositionIntPayload&>(::_GlobalPositionIntPayload_default_instance_);
}
inline const ::GlobalPositionIntPayload& DataStreamResponse::global_position_int() const {
  // @@protoc_insertion_point(field_get:DataStreamResponse.global_position_int)
  return _internal_global_position_int();
}
inline ::GlobalPositionIntPayload* DataStreamResponse::unsafe_arena_release_global_position_int() {
  // @@protoc_insertion_point(field_unsafe_arena_release:DataStreamResponse.global_position_int)
  if (_internal_has_global_position_int()) {
    clear_has_payload();
    ::GlobalPositionIntPayload* temp = _impl_.payload_.global_position_int_;
    _impl_.payload_.global_position_int_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void DataStreamResponse::unsafe_arena_set_allocated_global_position_int(::GlobalPositionIntPayload* global_position_int) {
  clear_payload();
  if (global_position_int) {
    set_has_global_position_int();
    _impl_.payload_.global_position_int_ = global_position_int;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DataStreamResponse.global_position_int)
}
inline ::GlobalPositionIntPayload* DataStreamResponse::_internal_mutable_global_position_int() {
  if (!_internal_has_global_position_int()) {
    clear_payload();
    set_has_global_position_int();
    _impl_.payload_.global_position_int_ = CreateMaybeMessage< ::GlobalPositionIntPayload >(GetArenaForAllocation());
  }
  return _impl_.payload_.global_position_int_;
}
inline ::GlobalPositionIntPayload* DataStreamResponse::mutable_global_position_int() {
  ::GlobalPositionIntPayload* _msg = _internal_mutable_global_position_int();
  // @@protoc_insertion_point(field_mutable:DataStreamResponse.global_position_int)
  return _msg;
}

// .AttitudePayload attitude = 12;
inline bool DataStreamResponse::_internal_has_attitude() const {
  return payload_case() == kAttitude;
}
inline bool DataStreamResponse::has_attitude() const {
  return _internal_has_attitude();
}
inline void DataStreamResponse::set_has_attitude() {
  _impl_._oneof_case_[0] = kAttitude;
}
inline void DataStreamResponse::clear_attitude() {
  if (_internal_has_attitude()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.attitude_;
    }
    clear_has_payload();
  }
}
inline ::AttitudePayload* DataStreamResponse::release_attitude() {
  // @@protoc_insertion_point(field_release:DataStreamResponse.attitude)
  if (_internal_has_attitude()) {
    clear_has_payload();
    ::AttitudePayload* temp = _impl_.payload_.attitude_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.attitude_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::AttitudePayload& DataStreamResponse::_internal_attitude() const {
  return _internal_has_attitude()
      ? *_impl_.payload_.attitude_
      : reinterpret_cast< ::AttitudePayload&>(::_AttitudePayload_default_instance_);
}
inline const ::AttitudePayload& DataStreamResponse::attitude() const {
  // @@protoc_insertion_point(field_get:DataStreamResponse.attitude)
  return _internal_attitude();
}
inline ::AttitudePayload* DataStreamResponse::unsafe_arena_release_attitude() {
  // @@protoc_insertion_point(field_unsafe_arena_release:DataStreamResponse.attitude)
  if (_internal_has_attitude()) {
    clear_has_payload();
    ::AttitudePayload* temp = _impl_.payload_.attitude_;
    _impl_.payload_.attitude_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void DataStreamResponse::unsafe_arena_set_allocated_attitude(::AttitudePayload* attitude) {
  clear_payload();
  if (attitude) {
    set_has_attitude();
    _impl_.payload_.attitude_ = attitude;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DataStreamResponse.attitude)
}
inline ::AttitudePayload* DataStreamResponse::_internal_mutable_attitude() {
  if (!_internal_has_attitude()) {
    clear_payload();
    set_has_attitude();
    _impl_.payload_.attitude_ = CreateMaybeMessage< ::AttitudePayload >(GetArenaForAllocation());
  }
  return _impl_.payload_.attitude_;
}
inline ::AttitudePayload* DataStreamResponse::mutable_attitude() {
  ::AttitudePayload* _msg = _internal_mutable_attitude();
  // @@protoc_insertion_point(field_mutable:DataStreamResponse.attitude)
  return _msg;
}

// .BatteryStatusPayload battery_status = 13;
inline bool DataStreamResponse::_internal_has_battery_status() const {
  return payload_case() == kBatteryStatus;
}
inline bool DataStreamResponse::has_battery_status() const {
  return _internal_has_battery_status();
}
inline void DataStreamResponse::set_has_battery_status() {
  _impl_._oneof_case_[0] = kBatteryStatus;
}
inline void DataStreamResponse::clear_battery_status() {
  if (_internal_has_battery_status()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.battery_status_;
    }
    clear_has_payload();
  }
}
inline ::BatteryStatusPayload* DataStreamResponse::release_battery_status() {
  // @@protoc_insertion_point(field_release:DataStreamResponse.battery_status)
  if (_internal_has_battery_status()) {
    clear_has_payload();
    ::BatteryStatusPayload* temp = _impl_.payload_.battery_status_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.battery_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::BatteryStatusPayload& DataStreamResponse::_internal_battery_status() const {
  return _internal_has_battery_status()
      ? *_impl_.payload_.battery_status_
      : reinterpret_cast< ::BatteryStatusPayload&>(::_BatteryStatusPayload_default_instance_);
}
inline const ::BatteryStatusPayload& DataStreamResponse::battery_status() const {
  // @@protoc_insertion_point(field_get:DataStreamResponse.battery_status)
  return _internal_battery_status();
}
inline ::BatteryStatusPayload* DataStreamResponse::unsafe_arena_release_battery_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:DataStreamResponse.battery_status)
  if (_internal_has_battery_status()) {
    clear_has_payload();
    ::BatteryStatusPayload* temp = _impl_.payload_.battery_status_;
    _impl_.payload_.battery_status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void DataStreamResponse::unsafe_arena_set_allocated_battery_status(::BatteryStatusPayload* battery_status) {
  clear_payload();
  if (battery_status) {
    set_has_battery_status();
    _impl_.payload_.battery_status_ = battery_status;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DataStreamResponse.battery_status)
}
inline ::BatteryStatusPayload* DataStreamResponse::_internal_mutable_battery_status() {
  if (!_internal_has_battery_status()) {
    clear_payload();
    set_has_battery_status();
    _impl_.payload_.battery_status_ = CreateMaybeMessage< ::BatteryStatusPayload >(GetArenaForAllocation());
  }
  return _impl_.payload_.battery_status_;
}
inline ::BatteryStatusPayload* DataStreamResponse::mutable_battery_status() {
  ::BatteryStatusPayload* _msg = _internal_mutable_battery_status();
  // @@protoc_insertion_point(field_mutable:DataStreamResponse.battery_status)
  return _msg;
}

inline bool DataStreamResponse::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void DataStreamResponse::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline DataStreamResponse::PayloadCase DataStreamResponse::payload_case() const {
  return DataStreamResponse::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// HeartbeatPayload

// uint32 type = 1;
inline void HeartbeatPayload::clear_type() {
  _impl_.type_ = 0u;
}
inline uint32_t HeartbeatPayload::_internal_type() const {
  return _impl_.type_;
}
inline uint32_t HeartbeatPayload::type() const {
  // @@protoc_insertion_point(field_get:HeartbeatPayload.type)
  return _internal_type();
}
inline void HeartbeatPayload::_internal_set_type(uint32_t value) {
  
  _impl_.type_ = value;
}
inline void HeartbeatPayload::set_type(uint32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:HeartbeatPayload.type)
}

// uint32 autopilot = 2;
inline void HeartbeatPayload::clear_autopilot() {
  _impl_.autopilot_ = 0u;
}
inline uint32_t HeartbeatPayload::_internal_autopilot() const {
  return _impl_.autopilot_;
}
inline uint32_t HeartbeatPayload::autopilot() const {
  // @@protoc_insertion_point(field_get:HeartbeatPayload.autopilot)
  return _internal_autopilot();
}
inline void HeartbeatPayload::_internal_set_autopilot(uint32_t value) {
  
  _impl_.autopilot_ = value;
}
inline void HeartbeatPayload::set_autopilot(uint32_t value) {
  _internal_set_autopilot(value);
  // @@protoc_insertion_point(field_set:HeartbeatPayload.autopilot)
}

// uint32 base_mode = 3;
inline void HeartbeatPayload::clear_base_mode() {
  _impl_.base_mode_ = 0u;
}
inline uint32_t HeartbeatPayload::_internal_base_mode() const {
  return _impl_.base_mode_;
}
inline uint32_t HeartbeatPayload::base_mode() const {
  // @@protoc_insertion_point(field_get:HeartbeatPayload.base_mode)
  return _internal_base_mode();
}
inline void HeartbeatPayload::_internal_set_base_mode(uint32_t value) {
  
  _impl_.base_mode_ = value;
}
inline void HeartbeatPayload::set_base_mode(uint32_t value) {
  _internal_set_base_mode(value);
  // @@protoc_insertion_point(field_set:HeartbeatPayload.base_mode)
}

// uint32 system_status = 4;
inline void HeartbeatPayload::clear_system_status() {
  _impl_.system_status_ = 0u;
}
inline uint32_t HeartbeatPayload::_internal_system_status() const {
  return _impl_.system_status_;
}
inline uint32_t HeartbeatPayload::system_status() const {
  // @@protoc_insertion_point(field_get:HeartbeatPayload.system_status)
  return _internal_system_status();
}
inline void HeartbeatPayload::_internal_set_system_status(uint32_t value) {
  
  _impl_.system_status_ = value;
}
inline void HeartbeatPayload::set_system_status(uint32_t value) {
  _internal_set_system_status(value);
  // @@protoc_insertion_point(field_set:HeartbeatPayload.system_status)
}

// uint32 custom_mode = 5;
inline void HeartbeatPayload::clear_custom_mode() {
  _impl_.custom_mode_ = 0u;
}
inline uint32_t HeartbeatPayload::_internal_custom_mode() const {
  return _impl_.custom_mode_;
}
inline uint32_t HeartbeatPayload::custom_mode() const {
  // @@protoc_insertion_point(field_get:HeartbeatPayload.custom_mode)
  return _internal_custom_mode();
}
inline void HeartbeatPayload::_internal_set_custom_mode(uint32_t value) {
  
  _impl_.custom_mode_ = value;
}
inline void HeartbeatPayload::set_custom_mode(uint32_t value) {
  _internal_set_custom_mode(value);
  // @@protoc_insertion_point(field_set:HeartbeatPayload.custom_mode)
}

// uint32 mavlink_version = 6;
inline void HeartbeatPayload::clear_mavlink_version() {
  _impl_.mavlink_version_ = 0u;
}
inline uint32_t HeartbeatPayload::_internal_mavlink_version() const {
  return _impl_.mavlink_version_;
}
inline uint32_t HeartbeatPayload::mavlink_version() const {
  // @@protoc_insertion_point(field_get:HeartbeatPayload.mavlink_version)
  return _internal_mavlink_version();
}
inline void HeartbeatPayload::_internal_set_mavlink_version(uint32_t value) {
  
  _impl_.mavlink_version_ = value;
}
inline void HeartbeatPayload::set_mavlink_version(uint32_t value) {
  _internal_set_mavlink_version(value);
  // @@protoc_insertion_point(field_set:HeartbeatPayload.mavlink_version)
}

// -------------------------------------------------------------------

// GlobalPositionIntPayload

// uint32 type = 1;
inline void GlobalPositionIntPayload::clear_type() {
  _impl_.type_ = 0u;
}
inline uint32_t GlobalPositionIntPayload::_internal_type() const {
  return _impl_.type_;
}
inline uint32_t GlobalPositionIntPayload::type() const {
  // @@protoc_insertion_point(field_get:GlobalPositionIntPayload.type)
  return _internal_type();
}
inline void GlobalPositionIntPayload::_internal_set_type(uint32_t value) {
  
  _impl_.type_ = value;
}
inline void GlobalPositionIntPayload::set_type(uint32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:GlobalPositionIntPayload.type)
}

// -------------------------------------------------------------------

// AttitudePayload

// uint32 type = 1;
inline void AttitudePayload::clear_type() {
  _impl_.type_ = 0u;
}
inline uint32_t AttitudePayload::_internal_type() const {
  return _impl_.type_;
}
inline uint32_t AttitudePayload::type() const {
  // @@protoc_insertion_point(field_get:AttitudePayload.type)
  return _internal_type();
}
inline void AttitudePayload::_internal_set_type(uint32_t value) {
  
  _impl_.type_ = value;
}
inline void AttitudePayload::set_type(uint32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:AttitudePayload.type)
}

// -------------------------------------------------------------------

// BatteryStatusPayload

// uint32 type = 1;
inline void BatteryStatusPayload::clear_type() {
  _impl_.type_ = 0u;
}
inline uint32_t BatteryStatusPayload::_internal_type() const {
  return _impl_.type_;
}
inline uint32_t BatteryStatusPayload::type() const {
  // @@protoc_insertion_point(field_get:BatteryStatusPayload.type)
  return _internal_type();
}
inline void BatteryStatusPayload::_internal_set_type(uint32_t value) {
  
  _impl_.type_ = value;
}
inline void BatteryStatusPayload::set_type(uint32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:BatteryStatusPayload.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_datastream_2eproto
