// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: datastream.proto

#include "datastream.pb.h"
#include "datastream.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* DataStreamService_method_names[] = {
  "/DataStreamService/receive",
};

std::unique_ptr< DataStreamService::Stub> DataStreamService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DataStreamService::Stub> stub(new DataStreamService::Stub(channel, options));
  return stub;
}

DataStreamService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_receive_(DataStreamService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::DataStreamResponse>* DataStreamService::Stub::receiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::DataStreamResponse>::Create(channel_.get(), rpcmethod_receive_, context, request);
}

void DataStreamService::Stub::async::receive(::grpc::ClientContext* context, const ::DataStreamRequest* request, ::grpc::ClientReadReactor< ::DataStreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::DataStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_receive_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::DataStreamResponse>* DataStreamService::Stub::AsyncreceiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::DataStreamResponse>::Create(channel_.get(), cq, rpcmethod_receive_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::DataStreamResponse>* DataStreamService::Stub::PrepareAsyncreceiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::DataStreamResponse>::Create(channel_.get(), cq, rpcmethod_receive_, context, request, false, nullptr);
}

DataStreamService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DataStreamService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< DataStreamService::Service, ::DataStreamRequest, ::DataStreamResponse>(
          [](DataStreamService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DataStreamRequest* req,
             ::grpc::ServerWriter<::DataStreamResponse>* writer) {
               return service->receive(ctx, req, writer);
             }, this)));
}

DataStreamService::Service::~Service() {
}

::grpc::Status DataStreamService::Service::receive(::grpc::ServerContext* context, const ::DataStreamRequest* request, ::grpc::ServerWriter< ::DataStreamResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


