// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastream.proto

#include "datastream.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR DataStreamRequest::DataStreamRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.conn_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DataStreamRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataStreamRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataStreamRequestDefaultTypeInternal() {}
  union {
    DataStreamRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataStreamRequestDefaultTypeInternal _DataStreamRequest_default_instance_;
PROTOBUF_CONSTEXPR DataStreamResponse::DataStreamResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.src_system_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.src_component_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct DataStreamResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataStreamResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataStreamResponseDefaultTypeInternal() {}
  union {
    DataStreamResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataStreamResponseDefaultTypeInternal _DataStreamResponse_default_instance_;
PROTOBUF_CONSTEXPR HeartbeatPayload::HeartbeatPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0u
  , /*decltype(_impl_.autopilot_)*/0u
  , /*decltype(_impl_.base_mode_)*/0u
  , /*decltype(_impl_.system_status_)*/0u
  , /*decltype(_impl_.custom_mode_)*/0u
  , /*decltype(_impl_.mavlink_version_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HeartbeatPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatPayloadDefaultTypeInternal() {}
  union {
    HeartbeatPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatPayloadDefaultTypeInternal _HeartbeatPayload_default_instance_;
PROTOBUF_CONSTEXPR GlobalPositionIntPayload::GlobalPositionIntPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GlobalPositionIntPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GlobalPositionIntPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GlobalPositionIntPayloadDefaultTypeInternal() {}
  union {
    GlobalPositionIntPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GlobalPositionIntPayloadDefaultTypeInternal _GlobalPositionIntPayload_default_instance_;
PROTOBUF_CONSTEXPR AttitudePayload::AttitudePayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AttitudePayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AttitudePayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AttitudePayloadDefaultTypeInternal() {}
  union {
    AttitudePayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AttitudePayloadDefaultTypeInternal _AttitudePayload_default_instance_;
PROTOBUF_CONSTEXPR BatteryStatusPayload::BatteryStatusPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BatteryStatusPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatteryStatusPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatteryStatusPayloadDefaultTypeInternal() {}
  union {
    BatteryStatusPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatteryStatusPayloadDefaultTypeInternal _BatteryStatusPayload_default_instance_;
static ::_pb::Metadata file_level_metadata_datastream_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_datastream_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_datastream_2eproto = nullptr;

const uint32_t TableStruct_datastream_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DataStreamRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DataStreamRequest, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::DataStreamRequest, _impl_.conn_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DataStreamResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::DataStreamResponse, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DataStreamResponse, _impl_.content_),
  PROTOBUF_FIELD_OFFSET(::DataStreamResponse, _impl_.src_system_),
  PROTOBUF_FIELD_OFFSET(::DataStreamResponse, _impl_.src_component_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::DataStreamResponse, _impl_.payload_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HeartbeatPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HeartbeatPayload, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::HeartbeatPayload, _impl_.autopilot_),
  PROTOBUF_FIELD_OFFSET(::HeartbeatPayload, _impl_.base_mode_),
  PROTOBUF_FIELD_OFFSET(::HeartbeatPayload, _impl_.system_status_),
  PROTOBUF_FIELD_OFFSET(::HeartbeatPayload, _impl_.custom_mode_),
  PROTOBUF_FIELD_OFFSET(::HeartbeatPayload, _impl_.mavlink_version_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GlobalPositionIntPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GlobalPositionIntPayload, _impl_.type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::AttitudePayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::AttitudePayload, _impl_.type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BatteryStatusPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BatteryStatusPayload, _impl_.type_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::DataStreamRequest)},
  { 8, -1, -1, sizeof(::DataStreamResponse)},
  { 22, -1, -1, sizeof(::HeartbeatPayload)},
  { 34, -1, -1, sizeof(::GlobalPositionIntPayload)},
  { 41, -1, -1, sizeof(::AttitudePayload)},
  { 48, -1, -1, sizeof(::BatteryStatusPayload)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_DataStreamRequest_default_instance_._instance,
  &::_DataStreamResponse_default_instance_._instance,
  &::_HeartbeatPayload_default_instance_._instance,
  &::_GlobalPositionIntPayload_default_instance_._instance,
  &::_AttitudePayload_default_instance_._instance,
  &::_BatteryStatusPayload_default_instance_._instance,
};

const char descriptor_table_protodef_datastream_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020datastream.proto\"2\n\021DataStreamRequest\022"
  "\014\n\004type\030\001 \001(\t\022\017\n\007conn_id\030\002 \001(\t\"\224\002\n\022DataS"
  "treamResponse\022\017\n\007content\030\001 \001(\t\022\022\n\nsrc_sy"
  "stem\030\002 \001(\t\022\025\n\rsrc_component\030\003 \001(\t\022&\n\thea"
  "rtbeat\030\n \001(\0132\021.HeartbeatPayloadH\000\0228\n\023glo"
  "bal_position_int\030\013 \001(\0132\031.GlobalPositionI"
  "ntPayloadH\000\022$\n\010attitude\030\014 \001(\0132\020.Attitude"
  "PayloadH\000\022/\n\016battery_status\030\r \001(\0132\025.Batt"
  "eryStatusPayloadH\000B\t\n\007payload\"\213\001\n\020Heartb"
  "eatPayload\022\014\n\004type\030\001 \001(\r\022\021\n\tautopilot\030\002 "
  "\001(\r\022\021\n\tbase_mode\030\003 \001(\r\022\025\n\rsystem_status\030"
  "\004 \001(\r\022\023\n\013custom_mode\030\005 \001(\r\022\027\n\017mavlink_ve"
  "rsion\030\006 \001(\r\"(\n\030GlobalPositionIntPayload\022"
  "\014\n\004type\030\001 \001(\r\"\037\n\017AttitudePayload\022\014\n\004type"
  "\030\001 \001(\r\"$\n\024BatteryStatusPayload\022\014\n\004type\030\001"
  " \001(\r2I\n\021DataStreamService\0224\n\007receive\022\022.D"
  "ataStreamRequest\032\023.DataStreamResponse0\001b"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_datastream_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_datastream_2eproto = {
    false, false, 687, descriptor_table_protodef_datastream_2eproto,
    "datastream.proto",
    &descriptor_table_datastream_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_datastream_2eproto::offsets,
    file_level_metadata_datastream_2eproto, file_level_enum_descriptors_datastream_2eproto,
    file_level_service_descriptors_datastream_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_datastream_2eproto_getter() {
  return &descriptor_table_datastream_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_datastream_2eproto(&descriptor_table_datastream_2eproto);

// ===================================================================

class DataStreamRequest::_Internal {
 public:
};

DataStreamRequest::DataStreamRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DataStreamRequest)
}
DataStreamRequest::DataStreamRequest(const DataStreamRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DataStreamRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.conn_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.conn_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.conn_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_conn_id().empty()) {
    _this->_impl_.conn_id_.Set(from._internal_conn_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:DataStreamRequest)
}

inline void DataStreamRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.conn_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.conn_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.conn_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DataStreamRequest::~DataStreamRequest() {
  // @@protoc_insertion_point(destructor:DataStreamRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DataStreamRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
  _impl_.conn_id_.Destroy();
}

void DataStreamRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DataStreamRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:DataStreamRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_.ClearToEmpty();
  _impl_.conn_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DataStreamRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DataStreamRequest.type"));
        } else
          goto handle_unusual;
        continue;
      // string conn_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_conn_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DataStreamRequest.conn_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DataStreamRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataStreamRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DataStreamRequest.type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_type(), target);
  }

  // string conn_id = 2;
  if (!this->_internal_conn_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_conn_id().data(), static_cast<int>(this->_internal_conn_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DataStreamRequest.conn_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_conn_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DataStreamRequest)
  return target;
}

size_t DataStreamRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DataStreamRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type());
  }

  // string conn_id = 2;
  if (!this->_internal_conn_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_conn_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DataStreamRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DataStreamRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DataStreamRequest::GetClassData() const { return &_class_data_; }


void DataStreamRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DataStreamRequest*>(&to_msg);
  auto& from = static_cast<const DataStreamRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DataStreamRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (!from._internal_conn_id().empty()) {
    _this->_internal_set_conn_id(from._internal_conn_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DataStreamRequest::CopyFrom(const DataStreamRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DataStreamRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataStreamRequest::IsInitialized() const {
  return true;
}

void DataStreamRequest::InternalSwap(DataStreamRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_, lhs_arena,
      &other->_impl_.type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.conn_id_, lhs_arena,
      &other->_impl_.conn_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata DataStreamRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datastream_2eproto_getter, &descriptor_table_datastream_2eproto_once,
      file_level_metadata_datastream_2eproto[0]);
}

// ===================================================================

class DataStreamResponse::_Internal {
 public:
  static const ::HeartbeatPayload& heartbeat(const DataStreamResponse* msg);
  static const ::GlobalPositionIntPayload& global_position_int(const DataStreamResponse* msg);
  static const ::AttitudePayload& attitude(const DataStreamResponse* msg);
  static const ::BatteryStatusPayload& battery_status(const DataStreamResponse* msg);
};

const ::HeartbeatPayload&
DataStreamResponse::_Internal::heartbeat(const DataStreamResponse* msg) {
  return *msg->_impl_.payload_.heartbeat_;
}
const ::GlobalPositionIntPayload&
DataStreamResponse::_Internal::global_position_int(const DataStreamResponse* msg) {
  return *msg->_impl_.payload_.global_position_int_;
}
const ::AttitudePayload&
DataStreamResponse::_Internal::attitude(const DataStreamResponse* msg) {
  return *msg->_impl_.payload_.attitude_;
}
const ::BatteryStatusPayload&
DataStreamResponse::_Internal::battery_status(const DataStreamResponse* msg) {
  return *msg->_impl_.payload_.battery_status_;
}
void DataStreamResponse::set_allocated_heartbeat(::HeartbeatPayload* heartbeat) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (heartbeat) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(heartbeat);
    if (message_arena != submessage_arena) {
      heartbeat = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, heartbeat, submessage_arena);
    }
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_set_allocated:DataStreamResponse.heartbeat)
}
void DataStreamResponse::set_allocated_global_position_int(::GlobalPositionIntPayload* global_position_int) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (global_position_int) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(global_position_int);
    if (message_arena != submessage_arena) {
      global_position_int = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, global_position_int, submessage_arena);
    }
    set_has_global_position_int();
    _impl_.payload_.global_position_int_ = global_position_int;
  }
  // @@protoc_insertion_point(field_set_allocated:DataStreamResponse.global_position_int)
}
void DataStreamResponse::set_allocated_attitude(::AttitudePayload* attitude) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (attitude) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(attitude);
    if (message_arena != submessage_arena) {
      attitude = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, attitude, submessage_arena);
    }
    set_has_attitude();
    _impl_.payload_.attitude_ = attitude;
  }
  // @@protoc_insertion_point(field_set_allocated:DataStreamResponse.attitude)
}
void DataStreamResponse::set_allocated_battery_status(::BatteryStatusPayload* battery_status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (battery_status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(battery_status);
    if (message_arena != submessage_arena) {
      battery_status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, battery_status, submessage_arena);
    }
    set_has_battery_status();
    _impl_.payload_.battery_status_ = battery_status;
  }
  // @@protoc_insertion_point(field_set_allocated:DataStreamResponse.battery_status)
}
DataStreamResponse::DataStreamResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DataStreamResponse)
}
DataStreamResponse::DataStreamResponse(const DataStreamResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DataStreamResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , decltype(_impl_.src_system_){}
    , decltype(_impl_.src_component_){}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  _impl_.src_system_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_system_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_src_system().empty()) {
    _this->_impl_.src_system_.Set(from._internal_src_system(), 
      _this->GetArenaForAllocation());
  }
  _impl_.src_component_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_component_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_src_component().empty()) {
    _this->_impl_.src_component_.Set(from._internal_src_component(), 
      _this->GetArenaForAllocation());
  }
  clear_has_payload();
  switch (from.payload_case()) {
    case kHeartbeat: {
      _this->_internal_mutable_heartbeat()->::HeartbeatPayload::MergeFrom(
          from._internal_heartbeat());
      break;
    }
    case kGlobalPositionInt: {
      _this->_internal_mutable_global_position_int()->::GlobalPositionIntPayload::MergeFrom(
          from._internal_global_position_int());
      break;
    }
    case kAttitude: {
      _this->_internal_mutable_attitude()->::AttitudePayload::MergeFrom(
          from._internal_attitude());
      break;
    }
    case kBatteryStatus: {
      _this->_internal_mutable_battery_status()->::BatteryStatusPayload::MergeFrom(
          from._internal_battery_status());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:DataStreamResponse)
}

inline void DataStreamResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , decltype(_impl_.src_system_){}
    , decltype(_impl_.src_component_){}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.src_system_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_system_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.src_component_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_component_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_payload();
}

DataStreamResponse::~DataStreamResponse() {
  // @@protoc_insertion_point(destructor:DataStreamResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DataStreamResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.content_.Destroy();
  _impl_.src_system_.Destroy();
  _impl_.src_component_.Destroy();
  if (has_payload()) {
    clear_payload();
  }
}

void DataStreamResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DataStreamResponse::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:DataStreamResponse)
  switch (payload_case()) {
    case kHeartbeat: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.heartbeat_;
      }
      break;
    }
    case kGlobalPositionInt: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.global_position_int_;
      }
      break;
    }
    case kAttitude: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.attitude_;
      }
      break;
    }
    case kBatteryStatus: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.battery_status_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void DataStreamResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:DataStreamResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _impl_.src_system_.ClearToEmpty();
  _impl_.src_component_.ClearToEmpty();
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DataStreamResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string content = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DataStreamResponse.content"));
        } else
          goto handle_unusual;
        continue;
      // string src_system = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_src_system();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DataStreamResponse.src_system"));
        } else
          goto handle_unusual;
        continue;
      // string src_component = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_src_component();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DataStreamResponse.src_component"));
        } else
          goto handle_unusual;
        continue;
      // .HeartbeatPayload heartbeat = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_heartbeat(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .GlobalPositionIntPayload global_position_int = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_global_position_int(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .AttitudePayload attitude = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_attitude(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .BatteryStatusPayload battery_status = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_battery_status(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DataStreamResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataStreamResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (!this->_internal_content().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_content().data(), static_cast<int>(this->_internal_content().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DataStreamResponse.content");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_content(), target);
  }

  // string src_system = 2;
  if (!this->_internal_src_system().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_src_system().data(), static_cast<int>(this->_internal_src_system().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DataStreamResponse.src_system");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_src_system(), target);
  }

  // string src_component = 3;
  if (!this->_internal_src_component().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_src_component().data(), static_cast<int>(this->_internal_src_component().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DataStreamResponse.src_component");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_src_component(), target);
  }

  // .HeartbeatPayload heartbeat = 10;
  if (_internal_has_heartbeat()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::heartbeat(this),
        _Internal::heartbeat(this).GetCachedSize(), target, stream);
  }

  // .GlobalPositionIntPayload global_position_int = 11;
  if (_internal_has_global_position_int()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::global_position_int(this),
        _Internal::global_position_int(this).GetCachedSize(), target, stream);
  }

  // .AttitudePayload attitude = 12;
  if (_internal_has_attitude()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(12, _Internal::attitude(this),
        _Internal::attitude(this).GetCachedSize(), target, stream);
  }

  // .BatteryStatusPayload battery_status = 13;
  if (_internal_has_battery_status()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(13, _Internal::battery_status(this),
        _Internal::battery_status(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DataStreamResponse)
  return target;
}

size_t DataStreamResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DataStreamResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string content = 1;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_content());
  }

  // string src_system = 2;
  if (!this->_internal_src_system().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_src_system());
  }

  // string src_component = 3;
  if (!this->_internal_src_component().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_src_component());
  }

  switch (payload_case()) {
    // .HeartbeatPayload heartbeat = 10;
    case kHeartbeat: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.heartbeat_);
      break;
    }
    // .GlobalPositionIntPayload global_position_int = 11;
    case kGlobalPositionInt: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.global_position_int_);
      break;
    }
    // .AttitudePayload attitude = 12;
    case kAttitude: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.attitude_);
      break;
    }
    // .BatteryStatusPayload battery_status = 13;
    case kBatteryStatus: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.battery_status_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DataStreamResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DataStreamResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DataStreamResponse::GetClassData() const { return &_class_data_; }


void DataStreamResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DataStreamResponse*>(&to_msg);
  auto& from = static_cast<const DataStreamResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DataStreamResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (!from._internal_src_system().empty()) {
    _this->_internal_set_src_system(from._internal_src_system());
  }
  if (!from._internal_src_component().empty()) {
    _this->_internal_set_src_component(from._internal_src_component());
  }
  switch (from.payload_case()) {
    case kHeartbeat: {
      _this->_internal_mutable_heartbeat()->::HeartbeatPayload::MergeFrom(
          from._internal_heartbeat());
      break;
    }
    case kGlobalPositionInt: {
      _this->_internal_mutable_global_position_int()->::GlobalPositionIntPayload::MergeFrom(
          from._internal_global_position_int());
      break;
    }
    case kAttitude: {
      _this->_internal_mutable_attitude()->::AttitudePayload::MergeFrom(
          from._internal_attitude());
      break;
    }
    case kBatteryStatus: {
      _this->_internal_mutable_battery_status()->::BatteryStatusPayload::MergeFrom(
          from._internal_battery_status());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DataStreamResponse::CopyFrom(const DataStreamResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DataStreamResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataStreamResponse::IsInitialized() const {
  return true;
}

void DataStreamResponse::InternalSwap(DataStreamResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.src_system_, lhs_arena,
      &other->_impl_.src_system_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.src_component_, lhs_arena,
      &other->_impl_.src_component_, rhs_arena
  );
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata DataStreamResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datastream_2eproto_getter, &descriptor_table_datastream_2eproto_once,
      file_level_metadata_datastream_2eproto[1]);
}

// ===================================================================

class HeartbeatPayload::_Internal {
 public:
};

HeartbeatPayload::HeartbeatPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HeartbeatPayload)
}
HeartbeatPayload::HeartbeatPayload(const HeartbeatPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HeartbeatPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.autopilot_){}
    , decltype(_impl_.base_mode_){}
    , decltype(_impl_.system_status_){}
    , decltype(_impl_.custom_mode_){}
    , decltype(_impl_.mavlink_version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mavlink_version_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.mavlink_version_));
  // @@protoc_insertion_point(copy_constructor:HeartbeatPayload)
}

inline void HeartbeatPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0u}
    , decltype(_impl_.autopilot_){0u}
    , decltype(_impl_.base_mode_){0u}
    , decltype(_impl_.system_status_){0u}
    , decltype(_impl_.custom_mode_){0u}
    , decltype(_impl_.mavlink_version_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HeartbeatPayload::~HeartbeatPayload() {
  // @@protoc_insertion_point(destructor:HeartbeatPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HeartbeatPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HeartbeatPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HeartbeatPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:HeartbeatPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mavlink_version_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.mavlink_version_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HeartbeatPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 autopilot = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.autopilot_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 base_mode = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.base_mode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 system_status = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.system_status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 custom_mode = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.custom_mode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 mavlink_version = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.mavlink_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HeartbeatPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HeartbeatPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_type(), target);
  }

  // uint32 autopilot = 2;
  if (this->_internal_autopilot() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_autopilot(), target);
  }

  // uint32 base_mode = 3;
  if (this->_internal_base_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_base_mode(), target);
  }

  // uint32 system_status = 4;
  if (this->_internal_system_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_system_status(), target);
  }

  // uint32 custom_mode = 5;
  if (this->_internal_custom_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_custom_mode(), target);
  }

  // uint32 mavlink_version = 6;
  if (this->_internal_mavlink_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_mavlink_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HeartbeatPayload)
  return target;
}

size_t HeartbeatPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HeartbeatPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_type());
  }

  // uint32 autopilot = 2;
  if (this->_internal_autopilot() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_autopilot());
  }

  // uint32 base_mode = 3;
  if (this->_internal_base_mode() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_base_mode());
  }

  // uint32 system_status = 4;
  if (this->_internal_system_status() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_system_status());
  }

  // uint32 custom_mode = 5;
  if (this->_internal_custom_mode() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_custom_mode());
  }

  // uint32 mavlink_version = 6;
  if (this->_internal_mavlink_version() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_mavlink_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeartbeatPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HeartbeatPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeartbeatPayload::GetClassData() const { return &_class_data_; }


void HeartbeatPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HeartbeatPayload*>(&to_msg);
  auto& from = static_cast<const HeartbeatPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HeartbeatPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_autopilot() != 0) {
    _this->_internal_set_autopilot(from._internal_autopilot());
  }
  if (from._internal_base_mode() != 0) {
    _this->_internal_set_base_mode(from._internal_base_mode());
  }
  if (from._internal_system_status() != 0) {
    _this->_internal_set_system_status(from._internal_system_status());
  }
  if (from._internal_custom_mode() != 0) {
    _this->_internal_set_custom_mode(from._internal_custom_mode());
  }
  if (from._internal_mavlink_version() != 0) {
    _this->_internal_set_mavlink_version(from._internal_mavlink_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HeartbeatPayload::CopyFrom(const HeartbeatPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HeartbeatPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartbeatPayload::IsInitialized() const {
  return true;
}

void HeartbeatPayload::InternalSwap(HeartbeatPayload* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HeartbeatPayload, _impl_.mavlink_version_)
      + sizeof(HeartbeatPayload::_impl_.mavlink_version_)
      - PROTOBUF_FIELD_OFFSET(HeartbeatPayload, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HeartbeatPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datastream_2eproto_getter, &descriptor_table_datastream_2eproto_once,
      file_level_metadata_datastream_2eproto[2]);
}

// ===================================================================

class GlobalPositionIntPayload::_Internal {
 public:
};

GlobalPositionIntPayload::GlobalPositionIntPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GlobalPositionIntPayload)
}
GlobalPositionIntPayload::GlobalPositionIntPayload(const GlobalPositionIntPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GlobalPositionIntPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:GlobalPositionIntPayload)
}

inline void GlobalPositionIntPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GlobalPositionIntPayload::~GlobalPositionIntPayload() {
  // @@protoc_insertion_point(destructor:GlobalPositionIntPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GlobalPositionIntPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GlobalPositionIntPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GlobalPositionIntPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:GlobalPositionIntPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GlobalPositionIntPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GlobalPositionIntPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GlobalPositionIntPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GlobalPositionIntPayload)
  return target;
}

size_t GlobalPositionIntPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GlobalPositionIntPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GlobalPositionIntPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GlobalPositionIntPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GlobalPositionIntPayload::GetClassData() const { return &_class_data_; }


void GlobalPositionIntPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GlobalPositionIntPayload*>(&to_msg);
  auto& from = static_cast<const GlobalPositionIntPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GlobalPositionIntPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GlobalPositionIntPayload::CopyFrom(const GlobalPositionIntPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GlobalPositionIntPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GlobalPositionIntPayload::IsInitialized() const {
  return true;
}

void GlobalPositionIntPayload::InternalSwap(GlobalPositionIntPayload* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GlobalPositionIntPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datastream_2eproto_getter, &descriptor_table_datastream_2eproto_once,
      file_level_metadata_datastream_2eproto[3]);
}

// ===================================================================

class AttitudePayload::_Internal {
 public:
};

AttitudePayload::AttitudePayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:AttitudePayload)
}
AttitudePayload::AttitudePayload(const AttitudePayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AttitudePayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:AttitudePayload)
}

inline void AttitudePayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AttitudePayload::~AttitudePayload() {
  // @@protoc_insertion_point(destructor:AttitudePayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AttitudePayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AttitudePayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AttitudePayload::Clear() {
// @@protoc_insertion_point(message_clear_start:AttitudePayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AttitudePayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AttitudePayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:AttitudePayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AttitudePayload)
  return target;
}

size_t AttitudePayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AttitudePayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AttitudePayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AttitudePayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AttitudePayload::GetClassData() const { return &_class_data_; }


void AttitudePayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AttitudePayload*>(&to_msg);
  auto& from = static_cast<const AttitudePayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AttitudePayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AttitudePayload::CopyFrom(const AttitudePayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AttitudePayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AttitudePayload::IsInitialized() const {
  return true;
}

void AttitudePayload::InternalSwap(AttitudePayload* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AttitudePayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datastream_2eproto_getter, &descriptor_table_datastream_2eproto_once,
      file_level_metadata_datastream_2eproto[4]);
}

// ===================================================================

class BatteryStatusPayload::_Internal {
 public:
};

BatteryStatusPayload::BatteryStatusPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:BatteryStatusPayload)
}
BatteryStatusPayload::BatteryStatusPayload(const BatteryStatusPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BatteryStatusPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.type_ = from._impl_.type_;
  // @@protoc_insertion_point(copy_constructor:BatteryStatusPayload)
}

inline void BatteryStatusPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BatteryStatusPayload::~BatteryStatusPayload() {
  // @@protoc_insertion_point(destructor:BatteryStatusPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BatteryStatusPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BatteryStatusPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BatteryStatusPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:BatteryStatusPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BatteryStatusPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BatteryStatusPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BatteryStatusPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BatteryStatusPayload)
  return target;
}

size_t BatteryStatusPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BatteryStatusPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 type = 1;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BatteryStatusPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BatteryStatusPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BatteryStatusPayload::GetClassData() const { return &_class_data_; }


void BatteryStatusPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BatteryStatusPayload*>(&to_msg);
  auto& from = static_cast<const BatteryStatusPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BatteryStatusPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BatteryStatusPayload::CopyFrom(const BatteryStatusPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BatteryStatusPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatteryStatusPayload::IsInitialized() const {
  return true;
}

void BatteryStatusPayload::InternalSwap(BatteryStatusPayload* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BatteryStatusPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datastream_2eproto_getter, &descriptor_table_datastream_2eproto_once,
      file_level_metadata_datastream_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::DataStreamRequest*
Arena::CreateMaybeMessage< ::DataStreamRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DataStreamRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::DataStreamResponse*
Arena::CreateMaybeMessage< ::DataStreamResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DataStreamResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::HeartbeatPayload*
Arena::CreateMaybeMessage< ::HeartbeatPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HeartbeatPayload >(arena);
}
template<> PROTOBUF_NOINLINE ::GlobalPositionIntPayload*
Arena::CreateMaybeMessage< ::GlobalPositionIntPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GlobalPositionIntPayload >(arena);
}
template<> PROTOBUF_NOINLINE ::AttitudePayload*
Arena::CreateMaybeMessage< ::AttitudePayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::AttitudePayload >(arena);
}
template<> PROTOBUF_NOINLINE ::BatteryStatusPayload*
Arena::CreateMaybeMessage< ::BatteryStatusPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BatteryStatusPayload >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
