// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: datastream.proto
#ifndef GRPC_datastream_2eproto__INCLUDED
#define GRPC_datastream_2eproto__INCLUDED

#include "datastream.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class DataStreamService final {
 public:
  static constexpr char const* service_full_name() {
    return "DataStreamService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::DataStreamResponse>> receive(::grpc::ClientContext* context, const ::DataStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::DataStreamResponse>>(receiveRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::DataStreamResponse>> Asyncreceive(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::DataStreamResponse>>(AsyncreceiveRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::DataStreamResponse>> PrepareAsyncreceive(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::DataStreamResponse>>(PrepareAsyncreceiveRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void receive(::grpc::ClientContext* context, const ::DataStreamRequest* request, ::grpc::ClientReadReactor< ::DataStreamResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::DataStreamResponse>* receiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::DataStreamResponse>* AsyncreceiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::DataStreamResponse>* PrepareAsyncreceiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::DataStreamResponse>> receive(::grpc::ClientContext* context, const ::DataStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::DataStreamResponse>>(receiveRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::DataStreamResponse>> Asyncreceive(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::DataStreamResponse>>(AsyncreceiveRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::DataStreamResponse>> PrepareAsyncreceive(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::DataStreamResponse>>(PrepareAsyncreceiveRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void receive(::grpc::ClientContext* context, const ::DataStreamRequest* request, ::grpc::ClientReadReactor< ::DataStreamResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::DataStreamResponse>* receiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::DataStreamResponse>* AsyncreceiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::DataStreamResponse>* PrepareAsyncreceiveRaw(::grpc::ClientContext* context, const ::DataStreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_receive_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status receive(::grpc::ServerContext* context, const ::DataStreamRequest* request, ::grpc::ServerWriter< ::DataStreamResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_receive() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive(::grpc::ServerContext* /*context*/, const ::DataStreamRequest* /*request*/, ::grpc::ServerWriter< ::DataStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestreceive(::grpc::ServerContext* context, ::DataStreamRequest* request, ::grpc::ServerAsyncWriter< ::DataStreamResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_receive<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_receive() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::DataStreamRequest, ::DataStreamResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::DataStreamRequest* request) { return this->receive(context, request); }));
    }
    ~WithCallbackMethod_receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive(::grpc::ServerContext* /*context*/, const ::DataStreamRequest* /*request*/, ::grpc::ServerWriter< ::DataStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::DataStreamResponse>* receive(
      ::grpc::CallbackServerContext* /*context*/, const ::DataStreamRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_receive<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_receive() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive(::grpc::ServerContext* /*context*/, const ::DataStreamRequest* /*request*/, ::grpc::ServerWriter< ::DataStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_receive() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive(::grpc::ServerContext* /*context*/, const ::DataStreamRequest* /*request*/, ::grpc::ServerWriter< ::DataStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestreceive(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_receive() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->receive(context, request); }));
    }
    ~WithRawCallbackMethod_receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status receive(::grpc::ServerContext* /*context*/, const ::DataStreamRequest* /*request*/, ::grpc::ServerWriter< ::DataStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* receive(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_receive() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::DataStreamRequest, ::DataStreamResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::DataStreamRequest, ::DataStreamResponse>* streamer) {
                       return this->Streamedreceive(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status receive(::grpc::ServerContext* /*context*/, const ::DataStreamRequest* /*request*/, ::grpc::ServerWriter< ::DataStreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedreceive(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::DataStreamRequest,::DataStreamResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_receive<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_receive<Service > StreamedService;
};


#endif  // GRPC_datastream_2eproto__INCLUDED
