// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: connection.proto
#ifndef GRPC_connection_2eproto__INCLUDED
#define GRPC_connection_2eproto__INCLUDED

#include "connection.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class ConnectionService final {
 public:
  static constexpr char const* service_full_name() {
    return "ConnectionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status connect(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::ConnectionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConnectionResponse>> Asyncconnect(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConnectionResponse>>(AsyncconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConnectionResponse>> PrepareAsyncconnect(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConnectionResponse>>(PrepareAsyncconnectRaw(context, request, cq));
    }
    virtual ::grpc::Status disconnect(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::DisconnectResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DisconnectResponse>> Asyncdisconnect(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DisconnectResponse>>(AsyncdisconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DisconnectResponse>> PrepareAsyncdisconnect(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DisconnectResponse>>(PrepareAsyncdisconnectRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void connect(::grpc::ClientContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void connect(::grpc::ClientContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void disconnect(::grpc::ClientContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void disconnect(::grpc::ClientContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ConnectionResponse>* AsyncconnectRaw(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ConnectionResponse>* PrepareAsyncconnectRaw(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::DisconnectResponse>* AsyncdisconnectRaw(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::DisconnectResponse>* PrepareAsyncdisconnectRaw(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status connect(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::ConnectionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConnectionResponse>> Asyncconnect(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConnectionResponse>>(AsyncconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConnectionResponse>> PrepareAsyncconnect(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConnectionResponse>>(PrepareAsyncconnectRaw(context, request, cq));
    }
    ::grpc::Status disconnect(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::DisconnectResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DisconnectResponse>> Asyncdisconnect(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DisconnectResponse>>(AsyncdisconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DisconnectResponse>> PrepareAsyncdisconnect(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DisconnectResponse>>(PrepareAsyncdisconnectRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void connect(::grpc::ClientContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response, std::function<void(::grpc::Status)>) override;
      void connect(::grpc::ClientContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void disconnect(::grpc::ClientContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response, std::function<void(::grpc::Status)>) override;
      void disconnect(::grpc::ClientContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ConnectionResponse>* AsyncconnectRaw(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ConnectionResponse>* PrepareAsyncconnectRaw(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::DisconnectResponse>* AsyncdisconnectRaw(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::DisconnectResponse>* PrepareAsyncdisconnectRaw(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_connect_;
    const ::grpc::internal::RpcMethod rpcmethod_disconnect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status connect(::grpc::ServerContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response);
    virtual ::grpc::Status disconnect(::grpc::ServerContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_connect() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::ConnectionRequest* /*request*/, ::ConnectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestconnect(::grpc::ServerContext* context, ::ConnectionRequest* request, ::grpc::ServerAsyncResponseWriter< ::ConnectionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_disconnect() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status disconnect(::grpc::ServerContext* /*context*/, const ::DisconnectRequest* /*request*/, ::DisconnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdisconnect(::grpc::ServerContext* context, ::DisconnectRequest* request, ::grpc::ServerAsyncResponseWriter< ::DisconnectResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_connect<WithAsyncMethod_disconnect<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_connect() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ConnectionRequest, ::ConnectionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response) { return this->connect(context, request, response); }));}
    void SetMessageAllocatorFor_connect(
        ::grpc::MessageAllocator< ::ConnectionRequest, ::ConnectionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ConnectionRequest, ::ConnectionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::ConnectionRequest* /*request*/, ::ConnectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* connect(
      ::grpc::CallbackServerContext* /*context*/, const ::ConnectionRequest* /*request*/, ::ConnectionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_disconnect() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::DisconnectRequest, ::DisconnectResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response) { return this->disconnect(context, request, response); }));}
    void SetMessageAllocatorFor_disconnect(
        ::grpc::MessageAllocator< ::DisconnectRequest, ::DisconnectResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::DisconnectRequest, ::DisconnectResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status disconnect(::grpc::ServerContext* /*context*/, const ::DisconnectRequest* /*request*/, ::DisconnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* disconnect(
      ::grpc::CallbackServerContext* /*context*/, const ::DisconnectRequest* /*request*/, ::DisconnectResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_connect<WithCallbackMethod_disconnect<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_connect() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::ConnectionRequest* /*request*/, ::ConnectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_disconnect() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status disconnect(::grpc::ServerContext* /*context*/, const ::DisconnectRequest* /*request*/, ::DisconnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_connect() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::ConnectionRequest* /*request*/, ::ConnectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestconnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_disconnect() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status disconnect(::grpc::ServerContext* /*context*/, const ::DisconnectRequest* /*request*/, ::DisconnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdisconnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_connect() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->connect(context, request, response); }));
    }
    ~WithRawCallbackMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::ConnectionRequest* /*request*/, ::ConnectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* connect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_disconnect() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->disconnect(context, request, response); }));
    }
    ~WithRawCallbackMethod_disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status disconnect(::grpc::ServerContext* /*context*/, const ::DisconnectRequest* /*request*/, ::DisconnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* disconnect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_connect() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ConnectionRequest, ::ConnectionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ConnectionRequest, ::ConnectionResponse>* streamer) {
                       return this->Streamedconnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::ConnectionRequest* /*request*/, ::ConnectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedconnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ConnectionRequest,::ConnectionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_disconnect() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::DisconnectRequest, ::DisconnectResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::DisconnectRequest, ::DisconnectResponse>* streamer) {
                       return this->Streameddisconnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status disconnect(::grpc::ServerContext* /*context*/, const ::DisconnectRequest* /*request*/, ::DisconnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streameddisconnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::DisconnectRequest,::DisconnectResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_connect<WithStreamedUnaryMethod_disconnect<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_connect<WithStreamedUnaryMethod_disconnect<Service > > StreamedService;
};


#endif  // GRPC_connection_2eproto__INCLUDED
