// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: connection.proto

#include "connection.pb.h"
#include "connection.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* ConnectionService_method_names[] = {
  "/ConnectionService/connect",
  "/ConnectionService/disconnect",
};

std::unique_ptr< ConnectionService::Stub> ConnectionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ConnectionService::Stub> stub(new ConnectionService::Stub(channel, options));
  return stub;
}

ConnectionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_connect_(ConnectionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_disconnect_(ConnectionService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ConnectionService::Stub::connect(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::ConnectionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ConnectionRequest, ::ConnectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_connect_, context, request, response);
}

void ConnectionService::Stub::async::connect(::grpc::ClientContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ConnectionRequest, ::ConnectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_connect_, context, request, response, std::move(f));
}

void ConnectionService::Stub::async::connect(::grpc::ClientContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_connect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ConnectionResponse>* ConnectionService::Stub::PrepareAsyncconnectRaw(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ConnectionResponse, ::ConnectionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_connect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ConnectionResponse>* ConnectionService::Stub::AsyncconnectRaw(::grpc::ClientContext* context, const ::ConnectionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncconnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ConnectionService::Stub::disconnect(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::DisconnectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DisconnectRequest, ::DisconnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_disconnect_, context, request, response);
}

void ConnectionService::Stub::async::disconnect(::grpc::ClientContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DisconnectRequest, ::DisconnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_disconnect_, context, request, response, std::move(f));
}

void ConnectionService::Stub::async::disconnect(::grpc::ClientContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_disconnect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DisconnectResponse>* ConnectionService::Stub::PrepareAsyncdisconnectRaw(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DisconnectResponse, ::DisconnectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_disconnect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DisconnectResponse>* ConnectionService::Stub::AsyncdisconnectRaw(::grpc::ClientContext* context, const ::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdisconnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

ConnectionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionService::Service, ::ConnectionRequest, ::ConnectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ConnectionRequest* req,
             ::ConnectionResponse* resp) {
               return service->connect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionService::Service, ::DisconnectRequest, ::DisconnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DisconnectRequest* req,
             ::DisconnectResponse* resp) {
               return service->disconnect(ctx, req, resp);
             }, this)));
}

ConnectionService::Service::~Service() {
}

::grpc::Status ConnectionService::Service::connect(::grpc::ServerContext* context, const ::ConnectionRequest* request, ::ConnectionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ConnectionService::Service::disconnect(::grpc::ServerContext* context, const ::DisconnectRequest* request, ::DisconnectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


